### PR TITLE
Add GPU tag to readme

### PR DESCRIPTION
**Pull request by thespad**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-piper/blob/main/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

### CODE REVIEW

**Review by Roxedus — APPROVED** [review]

**Comment by roryeckel** [comment]
I tested the following compose service on my server:
`piper:
        image: lscr.io/linuxserver/piper:gpu
        container_name: piper
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Chicago
        - PIPER_VOICE=en_US-hfc_female-medium
        - PIPER_LENGTH=1.0
        - PIPER_NOISE=0.667
        - PIPER_NOISEW=0.333
        - PIPER_SPEAKER=0
        - PIPER_PROCS=1
        volumes:
        - ./piper:/config
        ports:
            - 10200:10200
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
        memswap_limit: 0g
        runtime: nvidia`
It functions, but I noticed immediately that it was running on CPU instead of GPU like it's supposed to. Note that I am running a similar stack from LinuxServer.io for faster-whisper which does use the GPU correctly.

After investigating, I found that piper is expecting "--use-cuda", NOT "--cuda" like these changes propose. After fixing that, I get an error:
`ERROR:asyncio:Task exception was never retrieved

future: <Task finished name='Task-9' coro=<AsyncEventHandler.run() done, defined at /lsiopy/lib/python3.12/site-packages/wyoming/server.py:28> exception=FileNotFoundError(2, 'No such file or directory')>

Traceback (most recent call last):

  File "/lsiopy/lib/python3.12/site-packages/wyoming/server.py", line 35, in run

    if not (await self.handle_event(event)):

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lsiopy/lib/python3.12/site-packages/wyoming_piper/handler.py", line 99, in handle_event

    wav_file: wave.Wave_read = wave.open(output_path, "rb")

                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/wave.py", line 649, in open

    return Wave_read(f)

           ^^^^^^^^^^^^

  File "/usr/lib/python3.12/wave.py", line 282, in __init__

    f = builtins.open(f, 'rb')

        ^^^^^^^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: ''`

And after further debugging, it appears the empty string comes from piper throwing a segmentation fault upon starting. Not sure how to continue debugging from here, but it looks like GPU is not quite ready to work with this container

**Comment by thespad** [comment]
Unfortunately the piper binary silently ignores invalid CLI args, which makes testing it reliably extremely challenging.

**Comment by thespad** [comment]
Honestly the whole piper project seems to be kind of abandoned. No releases since 2023, few commits since then, issues and PRs largely ignored, readme doesn't even list the correct args for CUDA use. All my tests at the moment are resulting in segfaults but I'll see if I can make any progress.

**Comment by thespad** [comment]
It's not our image as it also segfaults in the nvidia pytorch container.

**Pull request merged**
